# General settings
title: Siddharth Jayashankar
title_html: "<b>{{ Siddharth Jayashankar }}</b>"
description:
    Siddharth Jayashankar's Webpage
domain: my-site.github.io       
url: "https://sidjay10.github.io"
#baseurl: "https://sidjay10.github.io"
image: "resources/ProfilePicture.jpg"


url: https://my-site.github.io  # the base hostname and protocol for your site, e.g. http://example.com


# Author
author: Siddharth Jayashankar

email:
  - sidjay [at] cmu.edu
  - sidjay64 [at] gmail.com
github_username: sidjay10
# keybase_username: gaalcaras
linkedin_username: siddharth-jayashankar
# author_website: https://sociologs.com
cv:
  url: assets/cv_gaalcaras.pdf

typing_text:
  - "There is an easy way and a hard way…"
  - "… The hard part is finding the easy way."
  - "When all else fails…" 
  - "Reboot!"
#  - "Experience is the name one gives to their mistakes."
  - "There’s no place like 127.0.0.1"
  - "When we had no computers…"
  - "… we had no programming problems either!"
  - "Live, Laugh and Love (me)? ❤️"

# Nav menu
nav_ext_links:
  - name: 📃 CV
    url:
     /resources/cv.pdf 
  # - name: 🖋️ Blog
  #   url:
  #     /blog

# Build settings
markdown: kramdown 
kramdown:
  extensions: ["tables", "fenced_code_blocks", "autolink", "footnotes", "with_toc_data"]
#theme: academic
remote_theme: sidjay10/academic
gems:
  - jekyll-feed
exclude:
  - jekyll_build.sh
  - Gemfile
  - Gemfile.lock
  - _academic
  - vendor

theme: jekyll-theme-cayman
